export const JUDETE = [
  { name: "Constanţa", countyCode: "CT" },
  { name: "Tulcea", countyCode: "TL" },
  { name: "Neamţ", countyCode: "NT" },
  { name: "Iaşi", countyCode: "IS" },
  { name: "Călăraşi", countyCode: "CL" },
  { name: "Sălaj", countyCode: "SJ" },
  { name: "Cluj", countyCode: "CJ" },
  { name: "Alba", countyCode: "AB" },
  { name: "Hunedoara", countyCode: "HD" },
  { name: "Gorj", countyCode: "GJ" },
  { name: "Dâmboviţa", countyCode: "DB" },
  { name: "Giurgiu", countyCode: "GR" },
  { name: "Bucureşti", countyCode: "B" },
  { name: "Vrancea", countyCode: "VR" },
  { name: "Vâlcea", countyCode: "VL" },
  { name: "Timiş", countyCode: "TM" },
  { name: "Teleorman", countyCode: "TR" },
  { name: "Suceava", countyCode: "SV" },
  { name: "Sibiu", countyCode: "SB" },
  { name: "Satu Mare", countyCode: "SM" },
  { name: "Prahova", countyCode: "PH" },
  { name: "Olt", countyCode: "OT" },
  { name: "Mureş", countyCode: "MS" },
  { name: "Mehedinţi", countyCode: "MH" },
  { name: "Maramureş", countyCode: "MM" },
  { name: "Ialomiţa", countyCode: "IL" },
  { name: "Harghita", countyCode: "HR" },
  { name: "Dolj", countyCode: "DJ" },
  { name: "Covasna", countyCode: "CV" },
  { name: "Caraş Severin", countyCode: "CS" },
  { name: "Buzău", countyCode: "BZ" },
  { name: "Braşov", countyCode: "BV" },
  { name: "Botoşani", countyCode: "BT" },
  { name: "Bistriţa Năsăud", countyCode: "BN" },
  { name: "Bihor", countyCode: "BH" },
  { name: "Bacău", countyCode: "BC" },
  { name: "Argeş", countyCode: "AG" },
  { name: "Arad", countyCode: "AR" },
  { name: "Brăila", countyCode: "BR" },
  { name: "Galaţi", countyCode: "GL" },
  { name: "Vaslui", countyCode: "VS" },
  { name: "Ilfov", countyCode: "IF" }
];
