export const JUDETE = [
  { name: "Constanţa", dps: "" },
  { name: "Tulcea", dps: "" },
  { name: "Neamţ", dps: "" },
  { name: "Iaşi", dps: "" },
  { name: "Călăraşi", dps: "" },
  { name: "Sălaj", dps: "" },
  { name: "Cluj", dps: "" },
  { name: "Alba", dps: "" },
  { name: "Hunedoara", dps: "" },
  { name: "Gorj", dps: "" },
  { name: "Dâmboviţa", dps: "" },
  { name: "Giurgiu", dps: "" },
  { name: "Bucureşti", dps: "" },
  { name: "Vrancea", dps: "" },
  { name: "Vâlcea", dps: "" },
  { name: "Timiş", dps: "" },
  { name: "Teleorman", dps: "" },
  { name: "Suceava", dps: "" },
  { name: "Sibiu", dps: "" },
  { name: "Satu Mare", dps: "" },
  { name: "Prahova", dps: "" },
  { name: "Olt", dps: "" },
  { name: "Mureş", dps: "" },
  { name: "Mehedinţi", dps: "" },
  { name: "Maramureş", dps: "" },
  { name: "Ialomiţa", dps: "" },
  { name: "Harghita", dps: "" },
  { name: "Dolj", dps: "" },
  { name: "Covasna", dps: "" },
  { name: "Caraş Severin", dps: "" },
  { name: "Buzău", dps: "" },
  { name: "Braşov", dps: "" },
  { name: "Botoşani", dps: "" },
  { name: "Bistriţa Năsăud", dps: "" },
  { name: "Bihor", dps: "" },
  { name: "Bacău", dps: "" },
  { name: "Argeş", dps: "" },
  { name: "Arad", dps: "" },
  { name: "Brăila", dps: "" },
  { name: "Galaţi", dps: "" },
  { name: "Vaslui", dps: "" },
  { name: "Ilfov", dps: "" }
];
